env:
  browser: true
  node: true
extends:
  - airbnb-base
  - 'plugin:vue/recommended'
  - prettier
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - '@typescript-eslint'
  - vue
  - prettier
rules:
  prettier/prettier: error
  '@typescript-eslint/no-unused-vars': error
  import/no-unresolved: off
  no-restricted-syntax: off
